### ISSUE TITLE
Code for CLIP score after masking

### ISSUE THREAD

**Issue by nazMahmoud** [locuslab/T-MARS#4]
Thanks for releasing the code! I would like to reproduce the results of the paper on the **medium** scale. 

From my understanding, the code released generates text detection bounding boxes for each image in the metadata. 

However, to reproduce the results in the paper, we need to re-compute CLIP score after masking. I do not see the **new** CLIP score saved in the metadata. What am I missing?

**Comment by pratyushmaini** [comment]
We saved the CLIP scores separately by masking the images based on the bounding boxes. This was done because the evaluation of CLIP score (only forward pass) can be done much faster than the detection process. We will be adding code to do the same shortly, but this should be straightforward (running a forward loop through the dataset, and masking images with mean color before sending to the CLIP model). Thanks for pointing this out.

**Comment by nazMahmoud** [comment]
Thank you for the prompt reply. Will be looking forward to the code release for recomputing CLIP score.

Meanwhile, are you planning to publish the uids for the medium scale? Also, have you attempted T-MARS on the large scale?

**Comment by SachinG007** [comment]
Hi @nazMahmoud ,
Thank you for your interest in our work. 
[Here](https://drive.google.com/drive/folders/1rV9Xz0jJyWBNVbrJpeJKXiUnzOc5aRhT?usp=sharing) are the data UIDs and Checkpoint for TMARS trained on DataComp medium scale.

We haven't yet tried on large scale.

Thanks
